import { Poppins } from "next/font/google"
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import NavBar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600']
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
  icon: [
    { url: "/favicon.ico" },
    { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    { url: "/favicon-512x512.png", sizes: "512x512", type: "image/png" },
    { url: "/favicon-192x192.png", sizes: "192x192", type: "image/png" },
  ],
},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} antialiased`}>
       <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
        <SidebarTrigger />
        <NavBar/>
        {children}
      </main>
    </SidebarProvider>
      </body>
    </html>
  );
}
